#DO NOT USE THIS FILE: The docker copose file does not work, the file is not finished.
version: '3'

services:
    waterfall:
        # build: ./waterfall
        image: waterfall-docker:latest
        stdin_open: true # docker run -i
        restart: unless-stopped
        # configs:
        #     - source: waterfall-config
        #       target: /app/container/config.yml
        volumes:
            - 'mc-waterfall:/app/container'
            # - '/app/waterfalltest:/app/container'
        ports:
            - "25565:25565"
        networks:
            - mc-internal
    lobby:
        # build: ./minecraft-server
        image: minecraft-docker
        stdin_open: true # docker run -i
        restart: unless-stopped
        volumes:
            - 'mc-lobby:/app/container'
            # - '/home/shared-plugins:/app/container/plugins'
        networks:
            - mc-internal
        deploy:
            resources:
                limits:
                    cpus: '2'
                    # memory: 2G
                # reservations:
                #     cpus: '0.25'
                    # memory: 0.5G
volumes:
    mc-waterfall:
    mc-lobby:

# configs:
#   waterfall-config:
#     external: true

networks:
    mc-internal: 
        # external:
        #     name: mc-global
#    internal-non-mc: {}
