FROM openjdk:16-alpine
EXPOSE 25565
WORKDIR /home/container

COPY ./data/preparation.sh /
COPY ./data/start.sh /home/container/

RUN apk add --no-cache --upgrade bash

CMD ["bash", "/preparation.sh" ]